config/routes.rb
Shopper::Engine.routes.draw do
  resource :cart, only: %i(show update), controller: 'cart'
  post 'cart/:type/:id', to: 'cart#add_product', as: :cart_add_product

  resources :order_item, only: :destroy

  get 'checkout/complete', to: 'checkout#complete', id: 'complete'
  resources :checkout, only: %i(show update)

  resources :orders, only: %i(index show)
end

app/models/concerns/shopper/order_aasm.rb
module Shopper
  module OrderAasm
    extend ActiveSupport::Concern

    included do
      include ::AASM

      enum state: %i(in_progress processing in_delivery delivered canceled)

      aasm column: :state, enum: true, whiny_transitions: false do
        state :in_progress, initial: true
        state :processing
        state :in_delivery
        state :delivered
        state :canceled

        event :place_order do
          transitions from: :in_progress, to: :processing
        end

        event :sent_to_client do
          transitions from: :processing, to: :in_delivery
        end

        event :end_delivery do
          transitions from: :in_delivery, to: :delivered
        end

        event :cancel do
          transitions from: [:processing, :in_delivery], to: :canceled
        end
      end
    end
  end
end

app/models/concerns/shopper/order_arithmetic_helpers.rb
module Shopper
  module OrderArithmeticHelpers
    def delivery_price
      delivery&.price || 0
    end

    def coupon_discount
      coupon&.discount || 0
    end

    def subtotal
      order_items.inject(0) { |sum, item| sum + item.subtotal }
    end

    def saved_by_coupon
      return 0 unless coupon_discount
      subtotal * coupon_discount / 100
    end

    def total
      subtotal - saved_by_coupon + delivery_price
    end
  end
end

app/models/concerns/shopper/order_item_arithmetic_helpers.rb
module Shopper
  module OrderItemArithmeticHelpers
    def subtotal
      quantity * product.price
    end
  end
end

app/models/concerns/shopper/order_number.rb
module Shopper
  module OrderNumber
    extend ActiveSupport::Concern

    included do
      before_create :generate_number

      def generate_number
        self.number = '#R'.ljust(10, rand.to_s[2..-1])
      end
    end
  end
end

app/models/concerns/shopper/order_product_helpers.rb
module Shopper
  module OrderProductHelpers
    def create_or_increment_product(type, id, quantity = 1)
      item = order_items.find_or_initialize_by(product_type: type.camelize, product_id: id)
      item.quantity = item.persisted? ? item.quantity + quantity.to_i : quantity
      item.save ? item : false
    end

    def create_or_update_product(type, id, quantity = 1)
      item = order_items.find_or_initialize_by(product_type: type.camelize, product_id: id)
      item.quantity = quantity
      item.save ? item : false
    end
  end
end

app/models/shopper/address.rb
module Shopper
  class Address < ApplicationRecord
    belongs_to :country
    belongs_to :addressable, polymorphic: true

    validates :country, presence: true

    def to_s
      "#{type}: #{country}, #{city}"
    end
  end
end

app/models/shopper/application_record.rb
module Shopper
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/shopper/billing_address.rb
module Shopper
  class BillingAddress < Address
  end
end

app/models/shopper/country.rb
module Shopper
  class Country < ApplicationRecord
    has_many :addresses

    validates :name, :code, presence: true, uniqueness: true

    def to_s
      name
    end
  end
end

app/models/shopper/coupon.rb
module Shopper
  class Coupon < ApplicationRecord
    belongs_to :order, optional: true

    validates :code, presence: true
    validates :discount,
              presence: true,
              numericality: {
                greater_than_or_equal_to: 0,
                less_than_or_equal_to: 100
              }
  end
end

app/models/shopper/credit_card.rb
module Shopper
  class CreditCard < ApplicationRecord
    belongs_to :order

    def to_s
      number
    end
  end
end

app/models/shopper/delivery.rb
module Shopper
  class Delivery < ApplicationRecord
    has_many :orders

    validates :price,
              numericality: { greater_than_or_equal_to: 0.00 },
              presence: true

    validates :min_days,
              presence: true,
              numericality: {
                greater_than: 0,
                less_than_or_equal_to: :max_days
              }

    validates :max_days,
              presence: true,
              numericality: { less_than_or_equal_to: 100 }

    def to_s
      "Delivery #{id}"
    end
  end
end

app/models/shopper/order.rb
module Shopper
  class Order < ApplicationRecord
    include Shopper::OrderAasm
    include Shopper::OrderArithmeticHelpers
    include Shopper::OrderNumber
    include Shopper::OrderProductHelpers

    belongs_to :customer,
               optional: true,
               polymorphic: true

    belongs_to :delivery, optional: true

    has_many :order_items, dependent: :destroy
    has_many :books, through: :order_items

    has_one :coupon, dependent: :nullify
    has_one :credit_card, dependent: :destroy

    has_one :billing_address,  as: :addressable, dependent: :destroy
    has_one :shipping_address, as: :addressable, dependent: :destroy

    def to_s
      "Order #{id}"
    end
  end
end

app/models/shopper/order_item.rb
module Shopper
  class OrderItem < ApplicationRecord
    include Shopper::OrderItemArithmeticHelpers

    belongs_to :order
    belongs_to :product, polymorphic: true

    validates :order, :product, :quantity, presence: true
    validates :quantity, numericality: {
      only_integer: true,
      greater_than_or_equal_to: 1
    }

    def to_s
      "#{quantity} #{product}"
    end
  end
end

app/models/shopper/shipping_address.rb
module Shopper
  class ShippingAddress < Address
  end
end

app/controllers/shopper/cart_controller.rb
module Shopper
  class CartController < ShopperController
    respond_to :js, only: [:add_product]

    def show
      present CartPage::CartPresenter.new(current_order)
    end

    def update
      CartPage::UpdateCart.call(params, current_order) do
        on(:invalid_coupon)  { flash[:error] = 'Invalid coupon code' }
        on(:invalid_product) { flash[:error] = 'Invalid product quantity' }
        on(:validate) do |*attr|
          present CartPage::CartPresenter.new(*attr)
          render 'show'
        end
        on(:ok) { redirect_to cart_path, flash: { success: 'Cart was updated successfully'  } }
      end
    end

    def add_product
      CartPage::AddProduct.call(params) do
        on(:invalid_product) do
          redirect_to main_app.root_path, flash: { error: 'Invalid product' }, js: true
        end
      end
    end
  end
end

app/controllers/shopper/checkout_controller.rb
module Shopper
  class CheckoutController < ShopperController
    include Shopper::CheckoutWizard

    before_action :fast_authenticate_customer!
    before_action :check_empty_cart
    before_action :check_accesability, except: :complete

    before_action :set_progress_presenter

    rescue_from Wicked::Wizard::InvalidStepError do |_|
      redirect_to cart_path, alert: t('checkout.failure.invalid_step')
    end

    rescue_from Shopper::CheckoutWizard::EmptyCardError do |_|
      redirect_to cart_path, alert: t('checkout.failure.cart_empty')
    end

    rescue_from Shopper::CheckoutWizard::CantAccessError do |_|
      redirect_to checkout_path(minimal_accessible_step),
                  flash: { error: t('checkout.failure.must_fill_previous') }
    end

    def show
      present step_presenter.new(current_order)
      render_wizard
    end

    def update
      Shopper::CheckoutPage::ProceedCheckout.call(current_order, params, step) do
        on(:invalid) do |*attrs|
          present step_presenter.new(*attrs)
          render_wizard
        end
        on(:ok) { redirect_to_next_step }
      end
    end

    def complete
      Shopper::CheckoutPage::PlaceOrder.call(current_order, params) do
        on(:invalid) { redirect_to cart_path, alert: t('checkout.failure.invalid_step') }
        on(:ok) do |old_order|
          present step_presenter.new(old_order)
          render_wizard
        end
      end
    end

    private

    def set_progress_presenter
      select_up_to_step = if step == :complete
                            :complete
                          else
                            minimal_accessible_step
                          end
      present Shopper::CheckoutPage::ProgressPresenter.new(
        steps,
        step,
        select_up_to_step
      ), for: :progress
    end

    def step_presenter
      "Shopper::CheckoutPage::#{step.capitalize}StepPresenter".constantize
    end
  end
end

app/controllers/shopper/order_item_controller.rb
module Shopper
  class OrderItemController < ShopperController
    def destroy
      @item = OrderItem.find(params[:id])
      authorize! :destroy, @item
      @item.destroy
      redirect_to cart_path
    rescue CanCan::AccessDenied
      redirect_to cart_path, alert: t('auth.access_denied')
    end
  end
end

app/controllers/shopper/orders_controller.rb
module Shopper
  class OrdersController < ShopperController
    before_action :authenticate_user!
    load_and_authorize_resource only: :show

    def index
      OrdersPage::GetOrders.call do
        on(:invalid_fiter) { flash[:error] = 'Invalid filter' }
        on(:ok) do |*attrs|
          present OrdersPage::OrdersPresenter.new(*attrs)
        end
      end
    end

    def show
      present OrdersPage::OrderPresenter.new(@order)
    end
  end
end

app/controllers/shopper/shopper_controller.rb
module Shopper
  class ShopperController < Shopper.parent_controller.constantize
  end
end

app/views/shopper/order_item/_table.html.haml
-# .hidden-xs
= render partial: 'shopper/order_item/table_desktop', locals: { items: items }
-# .visible-xs
-#   = render partial: 'shopper/order_item/table_phone', locals: { items: items }

app/views/shopper/order_item/_table_desktop.html.haml
%table.table.table-hover
  %tr.no-hover
    %th.col-pic.pl-0
      %span.in-grey-600 Product
    %th.col-title
    %th.col-price
      %span.in-grey-600 Price
    %th.col-quantity
      %span.in-grey-600 Quantity
    %th.col-total
      %span.in-grey-600 SubTotal
    %th.col-close
  - items.each do |item|
    = fields_for 'items[]', item do |item_fields|
      %tr
        %td
          .general-img-wrap-table
            = image_tag item.cover, class: 'cart-img-shadow pull-left width-full'
        %td
          %p.general-title= item.title
          - if item.description
            %p.in-grey-600.font-weight-light= item.description
        %td
          %span.font-16.in-gold-500= item.price
        %td
          .input-group.general-position{class: item.error_class, data: {quantity: true}}
            - if item.editable
              %a.input-link{href: "#"}
                %i.fa.fa-minus.line-height-40
              = item_fields.text_field :quantity, class: 'form-control quantity-input'
              %a.input-link{href: "#"}
                %i.fa.fa-plus.line-height-40
            - else
              %span.ml-30= item.quantity
        %td
          %span.font-16.in-gold-500= item.subtotal
        - if item.editable
          %td
            = link_to order_item_path(item), method: :delete, class: 'close general-cart-close' do
              %span{'aria-hidden': "true"} &times;

app/views/shopper/order_item/_table_phone.html.haml
- presenter.products.each do |product|
  .general-cart-item.divider-lg-bottom
    %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
      %span{'aria-hidden': "true"} &times;
    .general-img-wrap-table
      = image_tag product.cover, class: 'cart-img-shadow'
    %p.title= product.title
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500= product.price
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          = quantity_widget(product)
          -# .input-group
          -#   %a.input-link{href: "#"}
          -#     %i.fa.fa-minus.line-heaght-40
          -#   %input.form-control.quantity-input{type: "text"}
          -#   %a.input-link{href: "#"}
          -#     %i.fa.fa-plus.line-heaght-40
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500= product.subtotal